# Generated by Django 5.0.1 on 2024-01-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetTaxiForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromaddress', models.CharField(max_length=255)),
                ('toaddress', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
