# Generated by Django 5.0.1 on 2024-01-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_gettaxiform'),
    ]

    operations = [
        migrations.AddField(
            model_name='gettaxiform',
            name='action',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('unActive', 'Unactive'), ('Complete', 'Complete')], default='pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gettaxiform',
            name='username',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
