# Generated by Django 5.0.1 on 2024-01-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_gettaxiform_action_gettaxiform_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Driver'), (3, 'User')], default=3, null=True),
        ),
    ]
