# Generated by Django 5.0.1 on 2024-01-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_userregistration_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('DriverName', models.CharField(max_length=200)),
                ('DriverAddress', models.CharField(max_length=200)),
                ('VehicleModel', models.CharField(max_length=200)),
                ('VehicleNumber', models.CharField(max_length=20)),
                ('SeatCapacity', models.PositiveIntegerField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AmountPerKm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('SellAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DriverId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='userregistration',
            name='DriverId',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
